### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by irudnyts**
* Modify homework #1

### CODE REVIEW

**Comment by tvatter** [comment]
It looks really good, thanks a lot. I'm going to have a detailed look on Thursday, but I see almost nothing that I would like to change.

Just one thing: it seems that there is a lot of leftover stuff from 2018, e.g. `content/assignments/hw1/_index.html` or the links in `### Grades for HW1`. Would you mind correcting this?

**Comment by irudnyts** [comment]
Sure, will do (and also I guess I forgot to knit)! Thanks!

**Comment by tvatter** [comment]
Note that the website is "powered" by [blogdown](https://bookdown.org/yihui/blogdown/)

**Comment by irudnyts** [comment]
- Saying knit I meant "Serve Site". Thanks 👍 
- The folder structure is slightly changed. Hugo assumes to store [configuration files](https://gohugo.io/getting-started/directory-structure/) in `\data` folder. I have created `\skeletons` for skeletons of homework folder structure and `\datasets` to store real data files.
- Links are corrected but include brunch name `homework` (I guess I will need to correct them, once you merge the pull request into `master`).
- The section `Grades for HW1` is completely deleted (right?). No `Notes on the grading:`.
- `dsfba_homework1_skeleton.zip` is modified to be consistent with problem statements.
- Image `project_structure.png` is corrected to include the `data` folder.

**Comment by tvatter** [comment]
* Re folder structure: I think that both `datasets` and `skeletons` should be subfolders of `static` no? In any case, I will add a subfolder `slides` too and I would like to avoid having the root folder cluttered if possible.
* Re links: you can remove the branch name for the links so that it works as soon as we merge to master.
* Re grading: if we can leave the grading policy, I think that it's a good indication for the students. Or you would like to do it differently? I'm open to suggestions/ideas.

**Comment by irudnyts** [comment]
- Re folder structure: `datasets` and `skeletons` are in `static`.
- Re links: As I can understand, [the branch should be included in the link of the file](https://help.github.com/en/articles/getting-permanent-links-to-files). I have changed to `master`, so once you merge, should work.
- Re grading: `Notes on the grading` are copied from 2018.

**Pull request merged**
